spring:
  application:
    name: "spring-ai"
  ai:
    openai:
      base-url: https://openrouter.ai/api
      api-key: ${OPENROUTER_API_KEY}
      chat:
        options:
          model: deepseek/deepseek-chat-v3-0324:free

logging:
  level:
    org.springframework.ai.chat: debug
    com.quan: debug