spring:
  application:
    name: spring-ai-demo
  data:
    redis:
      host: localhost
      password: qwe123
      port: 16379
  ai:
    ollama:
      base-url: http://${SERVER}:11434
      chat:
        options:
          model: llava:7b
      embedding:
        enabled: false
        model: nomic-embed-text:latest
    openai:
      base-url: https://api.siliconflow.cn
      api-key: ${GJLD_APIKEY}
      chat:
        options:
          model: Qwen/Qwen2.5-7B-Instruct
      embedding:
        options:
          model: BAAI/bge-m3
    vectorstore:
      redis:
        index: quan_ai
        initialize-schema: true
        prefix: quan_ai

  # 设置上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.springframework.ai.chat: debug
    com.quan: debug